# Generated by Django 5.1.6 on 2025-03-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_admin_email_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
